name: glass_of_water
description: Course work 2022.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  introduction_screen : ^3.0.2
  percent_indicator: ^4.0.0
  lottie: ^1.2.2
  google_maps_flutter: ^2.1.3
  sensors_plus: ^1.3.1
  ml_linalg: ^13.9.0
  provider: ^6.0.5
  geolocator: ^9.0.2
  shimmer: ^2.0.0
  badges: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - animations/
