name: glass_of_water
description: Course work 2022.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  cupertino_icons: ^1.0.2
  google_fonts: ^2.3.1
  introduction_screen : ^3.0.2
  flutter_switch: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
